### ISSUE TITLE
Problem with conditional presence in inverted section

### ISSUE THREAD

**Issue by grrrwaaa** [Olivine-Labs/lustache#13]
The inverted section handling code implicitly assumes the value is a list, so it breaks when the value is e.g. a string:
```
model = {
person = {
{ name = "steve",  }, -- i.e. job = nil
{ name = "john", job="carpenter" },
},
}
```
```
{{#person}}
{{#job}} {{name}} is a {{job}} {{/job}}
{{^job}} {{name}} has no job {{/job}}
{{/person}}
```

/lustache/renderer.lua:29: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
	[C]: in function 'pairs'
	./modules/lustache/renderer.lua:29: in function 'is_array'
	./modules/lustache/renderer.lua:242: in function '_inverted'
	./modules/lustache/renderer.lua:63: in function 'callback'
	./modules/lustache/renderer.lua:211: in function '_section'
	./modules/lustache/renderer.lua:60: in function 'render'

The problem is that is_array() assumes the input is a table; this needs to be verified before calling it. Modifying line 242 as follows fixes the issue:
```
- if value == nil or value == false or (is_array(value) and #value == 0) then
+ if value == nil or value == false or (type(value) == "table" and is_array(value) and #value == 0) then
```

**Comment by brimworks** [comment]
Have you tried using the tip of master? For me, the tip of master works fine:

```
    local lustache = require("lustache")
    local view_model = {
        person = {
            { name = "steve",  }, -- i.e. job = nil
            { name = "john", job="carpenter" },
        },
    }
    print(lustache:render("{{#person}}{{#job}} {{name}} is a {{job}} {{/job}}{{^job}} {{name}} has no job {{/job}} {{/person}}", view_model))
```
Which prints:

` steve has no job   john is a carpenter`
