### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by gvieira** [Olivine-Labs/lustache#16]
Hi there,

I'm a Lua newbie and I think I'm doing something wrong.
Check my code (from lustache's README):

```lua
lustache = require "lustache"

view_model = {
  stooges = {
    { name = "Moe" },
    { name = "Larry" },
    { name = "Curly" }
  }
}

template = [[
{{#stooges}}
<b>{{name}}</b>
{{/stooges}}]]

output = lustache:render(template, view_model)

print(output)
```

Output:
```

<b>Moe</b>

<b>Larry</b>

<b>Curly</b>

```

My first guess was related to mustache, so I tried it in http://trymustache.com and the output was the following.

Output:
```
<b>Moe</b>
<b>Larry</b>
<b>Curly</b>

```

After, I tried doing the same using Ruby, because I know it better. Check it out:

```ruby
require 'mustache'

view_model = {
  :stooges => [
    { :name => "Moe" },
    { :name => "Larry" },
    { :name => "Curly" }
  ]
}

template = <<-EOS
{{#stooges}}
<b>{{name}}</b>
{{/stooges}}
EOS

output = Mustache.render(template, view_model)

puts output
```

Output:
```
<b>Moe</b>
<b>Larry</b>
<b>Curly</b>
```

Am I doing something wrong with lustache?

**Comment by hookenz** [comment]
I noticed this too. Placing it all on a single line fixed it for me.

**Comment by gvieira** [comment]
@hookenz Yeah, I tried that too and it worked, but this is not the default behavior of mustache.

**Comment by brimworks** [comment]
This appears to fix the problem:

https://github.com/Olivine-Labs/lustache/commit/f08de7953898a6c9d20b62d533755d1368771344

...basically I translated the code from here into Lua:

https://github.com/janl/mustache.js/blob/master/mustache.js

(and there was an off-by-one error due to 1 indexing in Lua)

**Comment by gvieira** [comment]
Hey @brimworks! Thanks for the follow up! Very nice. I couldn't test it, but it certainly make sense. :+1:
